###########################################################################
### Input files.

## This file contains the data.frame 'WRDS.Fama.French.factors'.
file.WRDS.Fama.French.Factors <-
  file.path(dir.data, "025_020_WRDS_Fama_French_Factors.RData")

## This file contains the classification results from Factiva.
file.factiva <- file.path(dir.data, "100_030_factiva.RData")

##File containing log-returns and essential information for each deal.
## The numbers at the end stand for the number of days omitted after
## the announcement date and before the resolution date.
file.returns.00.00 <- file.path(dir.data, "107_030_-_020_107_log-returns_00_00.RData");
file.returns.01.00 <- file.path(dir.data, "107_030_-_020_107_log-returns_01_00.RData");

###
###########################################################################


###########################################################################
### Output files.

## This file contains the combined data.frame 'TAret.factiva' generated by
## combine.TAret.factiva(), the Fama-French factor returns data.frame 'FF',
## and all regression result arrays 'By.Content.prior.And.Coverage.prior',
## 'By.Content.prior.Or.Coverage.prior', 'By.Content.prior', 'By.Coverage.prior',
## 'All.cases.including.NA.media' and 'Only.cases.with.NA.media'
file.time.series.regression.results <-
  file.path(dir.data, "180_031_-_025_100_107_time_series_regression_results.RData")
  
###
###########################################################################
